services:
  app-server:
    build: .
    hostname: server
    image: server-clj
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/certificate/server_certificate.crt:/etc/nginx/certs/server_certificate.crt:ro
      - ./resources/certificate/server.key:/etc/nginx/certs/server.key:ro
      - ./resources/certificate/john_authority.crt:/etc/nginx/certs/ca.crt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app-server
    links:
      - app-server

networks:
  default:
    driver: bridge
    name: mtls-server-side
