services:
  api01: &api
    build: .
    hostname: api-clj
    ports:
      - "3000:3000"
    image: rest-api-sample-clj
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/certificate/server_certificate.crt:/etc/nginx/certs/server_certificate.crt:ro
      - ./resources/certificate/server.key:/etc/nginx/certs/server.key
    depends_on:
      - api01
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"

networks:
  default:
    driver: bridge
    name: mtls-server-side
